plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
    modCompileOnly("com.terraformersmc:modmenu:11.0.3")
    implementation('com.github.usefulness:webp-imageio:0.10.2') {
        exclude group: 'org.jetbrains.kotlin'
    }
    shadowBundle('com.github.usefulness:webp-imageio:0.10.2') {
        exclude group: 'org.jetbrains.kotlin'
    }

    implementation('com.vladsch.flexmark:flexmark-html2md-converter:0.64.8') {
        exclude group: 'org.jetbrains.kotlin'
    }
    shadowBundle('com.vladsch.flexmark:flexmark-html2md-converter:0.64.8') {
        exclude group: 'org.jetbrains.kotlin'
    }
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: inputs.properties.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'

    exclude 'module-info.class'
    exclude '**/module-info.class'
    exclude 'kotlin/**'
    exclude 'META-INF/*.kotlin_module'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}